"""Application constants."""

# SMS Limits
SMS_MAX_LENGTH_GSM = 160
SMS_MAX_LENGTH_UNICODE = 70
SMS_CONCAT_LENGTH_GSM = 153
SMS_CONCAT_LENGTH_UNICODE = 67

# Protocol Names
PROTOCOL_SMPP = 'smpp'
PROTOCOL_HTTP = 'http'
PROTOCOL_KANNEL = 'kannel'

# Message Status
STATUS_PENDING = 'pending'
STATUS_QUEUED = 'queued'
STATUS_SENT = 'sent'
STATUS_DELIVERED = 'delivered'
STATUS_FAILED = 'failed'
STATUS_EXPIRED = 'expired'

# Default Settings
DEFAULT_RETRY_COUNT = 3
DEFAULT_RETRY_DELAY = 5
DEFAULT_WORKER_COUNT = 10

# SMPP Constants
SMPP_DEFAULT_PORT = 2775
SMPP_COMMAND_LENGTH = 4
SMPP_COMMAND_ID_LENGTH = 4
SMPP_COMMAND_STATUS_LENGTH = 4
SMPP_SEQUENCE_NUMBER_LENGTH = 4

# HTTP Status Codes
HTTP_OK = 200
HTTP_BAD_REQUEST = 400
HTTP_UNAUTHORIZED = 401
HTTP_NOT_FOUND = 404
HTTP_INTERNAL_SERVER_ERROR = 500
